### ISSUE TITLE
Scripts go to the incorrect location

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson-python#115]
The following snippet installs to `.data/data/bin/example-script`, instead of `.data/scripts/example-script`.

```meson
install_data(
    'example-script.py',
    rename: 'example-script',
    install_dir: get_option('bindir'),
)
```

This happens because Meson returns the full path in this situation, but still, we should not be putting the file in `.data/data` like this.

**Comment by rgommers** [comment]
gh-148 improves a test for this. Meson master uses `{bindir}`, so the file lands in `scripts/`. Meson 0.63.2 still contains absolute paths, so the file lands in `data/bin/`. So once we make Meson 0.64 the minimum supported version, this will fix itself and we can clean up the test for it.
