### ISSUE TITLE
Document support for installing python scripts

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson-python#138]
How can I install python scripts with `meson-python` replacing setuptool's `console_scripts` `enty_point` or `[project.scripts]` in `pyproject.toml`? If there is a vision of how this should look like I'm happy to try to work on the support.

**Comment by FFY00** [comment]
Hi, `project.scripts` (from [PEP 621](https://peps.python.org/pep-0621/)) is supported, so you may use it as you would on any other Python build backend (example: https://peps.python.org/pep-0621/#example). Alternatively, if you need to install any other scripts, `executable`s in Meson are included in the package as scripts.

**Comment by dnicolodi** [comment]
Great. From the documentation it is not evident which features of PEP621 are supported.

**Comment by FFY00** [comment]
Noted. Thanks!
