### ISSUE TITLE
Only use and depend on patchelf if it is actually needed

### ISSUE THREAD

**Issue by rgommers** [mesonbuild/meson-python#158]
This is a follow-up to gh-125. The fix for that issue ensured that runpath entries that were not needed are no longer inserted. The original issue description of gh-125 was also about the dependency on `patchelf` on Linux. This is still injected on Linux when `patchelf` is not already installed, in `get_requires_for_build_wheel`. Ideally this would not be the case, because `patchelf` is not needed unless an rpath/runpath entry needs to be made. That is typically not the case. And it can lead to problems - in gh-125 a `patchelf` build from source was triggered and it failed.

At the moment we don't have any real-world users (AFAIK) that do require `patchelf`. So a useful follow-up would be to not require `patchelf` unless it is actually needed. How to achieve this is TBD, there are various options - from a dedicated flag for it in `pyproject.toml`, to simply documenting how it works and that end users need to take care of this themselves, to perhaps smarter solutions.

This isn't urgent, but it would be a nice improvement.

**Comment by FFY00** [comment]
Fixed by #64
