### ISSUE TITLE
Inconsistent version constraints

### ISSUE THREAD

**Issue by awvwgk** [mesonbuild/meson-python#164]
Is there a reason for the discrepancy between required meson versions in build and run?

Build dependencies:

https://github.com/FFY00/meson-python/blob/4acffd793c3d70ac7fe36e8869c2cf88b16ad441/pyproject.toml#L5

Run dependencies:

https://github.com/FFY00/meson-python/blob/4acffd793c3d70ac7fe36e8869c2cf88b16ad441/pyproject.toml#L29

---

Also, if the tests require a newer version of `pyproject-metadata` how can be sure an older version of it will work correctly for running `meson-python` in user projects?

Run dependencies:

https://github.com/FFY00/meson-python/blob/4acffd793c3d70ac7fe36e8869c2cf88b16ad441/pyproject.toml#L31

Test dependencies:

https://github.com/FFY00/meson-python/blob/4acffd793c3d70ac7fe36e8869c2cf88b16ad441/pyproject.toml#L48

**Comment by rgommers** [comment]
> Is there a reason for the discrepancy between required meson versions in build and run?

Just an oversight I believe. `meson-python` itself is very simple so sdist/wheels for it can be built with older `meson` versions without issues. But for consistency we should set these to be the same anyway.



> Also, if the tests require a newer version of `pyproject-metadata` how can be sure an older version of it will work correctly for running `meson-python` in user projects?

That looks like a worse inconsistency. We need a bug fix in `pyproject-metadata` 0.6, so that should be the minimum version at runtime.

**Comment by FFY00** [comment]
> That looks like a worse inconsistency. We need a bug fix in `pyproject-metadata` 0.6, so that should be the minimum version at runtime.

For future reference, since we check the metadata output in the tests, if `pyproject-metadata` changes the output slightly, we may need a higher test version.
