### ISSUE TITLE
Organisational: move this repo to a GitHub organization

### ISSUE THREAD

**Issue by rgommers** [mesonbuild/meson-python#168]
When starting this project we  (@FFY00 and I) discussed where to create a repo. At the time the thought was that it doesn't matter too much, because the intent is to finish it and move it into Meson (xref "Expose a PEP 517 backend" issue: https://github.com/mesonbuild/meson/issues/7863). However, as is often the case, reality messes with the initial plan - writing a full-featured PEP 517 backend has turned out to be a little more complicated than we thought initially.

It's now time to move this repo to a GitHub organization, so it can continue to grow, adding regular teams with permissions, etc. Also for adopters, it tends to inspire more confidence if an open source project is under a GitHub org rather than a personal fork.

There are three main choices:
1. Under the Meson project: https://github.com/mesonbuild/
2. Under the PyPA: https://github.com/pypa/
3. In a brand-new org just for this project

Given our original plan and how closely `meson-python` is linked with Meson, moving it under the Meson org seems like the preferred solution. And under the PyPA the second one. 

@eli-schwartz can we ask for your opinion here? Does it sound like a good and feasible idea move this repo to the Meson org, and if so how should we propose this to the Meson devs?

**Comment by jpakkane** [comment]
If you want to move this under Meson organization just let me know what needs to be done on our side.

**Comment by eli-schwartz** [comment]
And there we go. :)

**Comment by rgommers** [comment]
Great, thanks @jpakkane and @eli-schwartz!

Here is what I'm thinking:
- Create a couple of new teams under the `mesonbuild` GitHub org:
  - `meson-python-devs` (for write access to the repo)
  - `meson-python-triage` (for triage access to the repo)
  - `meson-python-admins` (for admin access to the repo)
- Make @FFY00 and myself [team maintainers](https://docs.github.com/en/organizations/organizing-members-into-teams/assigning-the-team-maintainer-role-to-a-team-member) of those teams, so we have the ability to invite others
- Once that is done, maybe @FFY00 is able to transfer this repo to the `mesonbuild` org. If not, @FFY00 can make @jpakkane a co-owner of this repo so @jpakkane can do the transfer.
- After that, the `meson-python` repo permissions should be granted to the new teams

That should be it permissions-wise. We may have to update CI integrations, but with admin rights to the repo that should all work.

@FFY00 does that sound good? Anything else you can think of?

**Comment by jpakkane** [comment]
I created the admin group first and sent invites. I'm not sure if I need to create a codeless repository for the transfer too.

**Comment by FFY00** [comment]
I can't transfer it, I need repo create access in the organization, can you grant it temporarily?

**Comment by jpakkane** [comment]
I could not easily figure out how to do it so I imported myself. You should now have admin rights to that repo.

**Comment by FFY00** [comment]
That loses all the issues and PRs. When I am back on the computer I will write down all the steps to grant repo create permission to an organization user.

**Comment by jpakkane** [comment]
Ping?

**Comment by FFY00** [comment]
Sorry for the delay. The only way I've found to do this is to enable this permission for all organization members temporarily.

I have started a transfer request to your personal account, please accept it and then transfer to the Meson org. Thanks!

**Comment by jpakkane** [comment]
It should be good now. Is everything as you need it?

**Comment by rgommers** [comment]
Everything looks like it's in the right place, thanks @jpakkane and @FFY00.

@FFY00 I guess we can close this; if we're missing anything like CI hooks, we can deal with that as it shows up?

**Comment by FFY00** [comment]
Yep, all good so far. I will update the CI/docs as needed later today.
