### ISSUE TITLE
Sage CI: openSUSE 15.4 cannot work with meson-python because it only has Python 3.6 stack

### ISSUE THREAD

**Issue by bnavigator** [mesonbuild/meson-python#172]
This won't work:

https://github.com/FFY00/meson-python/blob/1a4882e9f6d973934185a0f5fec052750983b960/.github/workflows/ci-sage.yml#L100

openSUSE Leap 15.X and the corresponding SLE only have a full module stack for Python 3.6. As that is EOL and meson-python requires Python >= 3.7, testing on that distribution will never work.

However, you could add Tumbleweed if that is available from Sagemath or use the [openSUSE Build Service directly](https://openbuildservice.org/2021/05/31/scm-integration/).

**Comment by rgommers** [comment]
Ah that is good to know - one less CI job that's failing. Given that you have already packaged `meson-python` and tests are passing, it's probably not super urgent to add a new job. So let's only do that if it's already available. @mkoeppe is this easy to switch within the Sage CI job?

**Comment by mkoeppe** [comment]
That's right, on `opensuse-15.4` Sage rejects the system python3 and builds and uses its own copy of python 3.10.x
```
Checking whether SageMath should install SPKG python3...
checking whether any of bzip2 liblzma libffi is installed as or will be installed as SPKG... no
checking for python3 >= 3.8.0, < 3.11.0 with modules sqlite3, ctypes, math, hashlib, crypt, socket, zlib, distutils.core, ssl, ensurepip... 
checking ... whether /usr/bin/python3 is good... no, Python 3.6.15 is too old

configure: to try to use a different system python, use ./configure --with-python=/path/to/python
configure: no suitable system package found for SPKG python3
```
(see for example https://github.com/FFY00/meson-python/actions/runs/3234058687/jobs/5298285181)

Still testing on this platform may be useful for meson-python because the test suite reveals a problem with something on the platform.

Yes, `opensuse-tumbleweed` can be added to ci-sage.yml just by adding this name to the list

**Comment by bnavigator** [comment]
> checking ... whether /usr/bin/python3 is good... no, Python 3.6.15 is too old

There would be the `/usr/bin/python3.10` interpreter from openSUSE, but almost everything else has to come from Sage or PyPI.

Ande meson is at 0.59.4

**Comment by mkoeppe** [comment]
Thanks for the pointer. We currently do not test Sage with this interpreter. I'll look into this in https://trac.sagemath.org/ticket/32182

Sage only needs the interpreter. We use a venv without system site packages.

**Comment by dnicolodi** [comment]
Fixed.
