### ISSUE TITLE
Build fails when no py_micro version is specified in the metadata

### ISSUE THREAD

**Issue by jejaccard** [mesonbuild/meson-python#186]
Hello,

Currently `_validate_metadata`  prevents the build from completing if in pyproject.toml the version specifier does not contain PY_MICRO. E.G. the build fails if `requires-python = "<=3.10"` and I build using any python 3.10.x version.

Although being very easy to quickfix (change to `requires-python = "<3.11`) and a really small issue, I do not think it is the intended behavior.

As a more general matter, it may not be suitable to do this version check at all in meson-python since anyway the version specifier is copied in the METADATA file in the wheel which will prevent the installation when using `pip install`. 
It would also allow to build for previous python version with a higher one (e.g. build for 3.9 in 3.10) which could be a nice feature for pure python packages (setuptools allows that). And if the user really wants to prevent the build, it can still be prevented in the meson.build file via `py.language_version().version_compare()`.
I think that this is in line with the host machine/build machine philosophy of meson.

Big thanks to the dev team for this awesome package!

Jérémie

**Comment by FFY00** [comment]
Thank you Jérémie.

I understand it may not be intuitive, but this is the intended behavior. It comes from the version specifier specification, which says versions should be zero-paded to match the lenght of the version you are comparing to.

https://peps.python.org/pep-0440/#inclusive-ordered-comparison

**Comment by jejaccard** [comment]
I did not know the existence of this specification and it is indeed the correct behavior. It is still weird to me that pip is not compliant with PEP 440 (for example, it allows to install a package with `requires-python = "<=3.10"` on python 3.10.4).

Anyway sorry for the disturbance and thanks Filipe for the clarification!
