### ISSUE TITLE
Use introspection to generate wheel tags

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson-python#190]
In #189 it become clear that it is not really possible to map extension filenames to wheel tags in a robust way: the file names do not contain ABI tags. However, the python implementation which is running meson-python is the same as the one for which the extensions are being built. Therefore, we can introspect the interpreter to get the wheel tags. Using the `packaging` module seems the most straightforward way to do this.

The only open question is how to decide to go for an implementation ABI tag or a stable ABI tag. I don't think that Meson python module has a way to generate extension modules for the stable ABI, so maybe this is not important right now. But the current meson-python has some support to auto-detect this, so maybe it should be supported somehow.

Should we keep validating the extension filename suffixes against the suffixes accepted by the Python interpreter? The list of accepted suffixes is provided in `importlib.machinery.EXTENSION_SUFFIXES` thus the check is easily implemented. Should deeper checks be done?

**Comment by FFY00** [comment]
We should do both. Look at the wheel tags to decide if the stable ABI should be used, and use introspection to generate the tags.

**Comment by dnicolodi** [comment]
I'll have a look at implementing this.
