### ISSUE TITLE
Usage of private APIs in wheel

### ISSUE THREAD

**Issue by henryiii** [mesonbuild/meson-python#192]
Currently, meson-python uses the `wheel` package, which does not have a public API (the author has been warning everyone of this for years). The current API is going to be removed in https://github.com/pypa/wheel/pull/472. Solutions:

The removal will come with a new public API, so once that gets merged, this could be set up to use that. Maybe adding a limit would be in order, too, until that happens (not fond of limits, but might be in order here, especially as it would only be in the build wheel requires hook).

The pypa/distlib library has a public Wheel interface (this is what I've been using in scikit-build-core to be future-proof for the incoming wheel change).

And of course, it can be hand rolled too.

**Comment by dnicolodi** [comment]
I love the constant churn around the python packaging specification and tools. I had a look at `distlib` and its API is awful. The public API for the `wheel` package has been in the works since 2018. I think the wise thing is to wait and see how things pan out.

**Comment by rgommers** [comment]
Ah yes, fun. I agree we need an upper bound here, to avoid building from source breaking at some arbitrary time whenever `wheel` removes this private API. 

> And of course, it can be hand rolled too.

Not a fan of that - the alternative to an upper bound is to vendor an existing implementation, not write yet-another-one.

**Comment by FFY00** [comment]
We just need something that subclasses `zipfile.ZipFile` and logs the hashes of the written files to the metadata, I think. So, we could just extract that from `wheel` and provide it in a new package while they design a public API.
