### ISSUE TITLE
Still issues on windows ... probably documentation.

### ISSUE THREAD

**Issue by kif** [mesonbuild/meson-python#244]
While releasing `fabio`, I encountered again the issue #187 (sorry I could not reopen the issue).
On windows, the build mechanism requires to pass `--buildtype plain` to the meson `configure` stage (is this a bug at the meson stage ?).
One work-around I found was to use twice the `--config-setting` to provide the key as first option to meson  and the value for the  second option. This gives a command line like this:
 
`python -m build  --config-setting setup-args="--buildtype" --config-setting setup-args="plain"`

This looks pretty obfuscated and totally un-pythonic to me. Maybe there is a better solution I did not found, if not this "work-around"  should be documented at minima.

**Comment by dnicolodi** [comment]
> On windows, the build mechanism requires to pass `--buildtype plain` to the meson `configure` stage

Is this a peculiarity of `fabio`? Other projects clearly do not have this requirement. What goes wrong if you do not specify this?

For the command line,
```
python -m build -Csetup-args=--buildtype=plain
```
or 
```
python -m build -Csetup-args=-Dbuildtype=plain
```
work and do not seem that unreasonable to me. However, note that meson-python has no control over how the command line arguments are parsed, that's build territory.

> this "work-around" should be documented at minima.

Work around for what?

**Comment by dnicolodi** [comment]
There are many software packages named "fabio". Assuming that the project you are mentioning is this one https://github.com/silx-kit/fabio I had a quick look at its Meson build definition and I found a few things that do not match current best practices.

**Comment by kif** [comment]
Indeed the `fabio` project I am referring to is the one from silx-kit (300 scientific projects depend on it, so it is small but larger than  just a pet-project). `fabio` has nothing special, this is what make's it appealing to start the migration with it :)

Both of the solution you proposed work well and look much nicer than the work-around I found. Thanks

It is not that I want to build with the option `--buildtype=plain`, it is that without this option, the build fails because of a missing library at the link time:
```
[9/20] Linking target fabio/ext/cf_io.pyd
FAILED: fabio/ext/cf_io.pyd
"link"  /MACHINE:x64 /OUT:fabio/ext/cf_io.pyd fabio/ext/cf_io.pyd.p/meson-generated_fabio_ext_cf_io.pyx.c.obj fabio/ext/cf_io.pyd.p/src_columnfile.c.obj "/nologo" "/release" "/nologo" "/DLL" "/IMPLIB:fabio\ext\cf_io.lib" "c:\python\3.8\libs\python38.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
LINK : fatal error LNK1104: cannot open file 'python38_d.lib'
[14/20] Compiling C object fabio/ext/mar345_IO....p/meson-generated_fabio_ext_mar345_IO.pyx.c.ob
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\kieffer\py38\lib\site-packages\pep517\in_process\_in_process.py", line 351, in <module>
    main()
  File "C:\Users\kieffer\py38\lib\site-packages\pep517\in_process\_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Users\kieffer\py38\lib\site-packages\pep517\in_process\_in_process.py", line 249, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "C:\Users\kieffer\AppData\Local\Temp\build-env-vu8fa4mh\lib\site-packages\mesonpy\__init__.py", line 1061, in build_wheel
    return project.wheel(out).name
  File "C:\Users\kieffer\AppData\Local\Temp\build-env-vu8fa4mh\lib\site-packages\mesonpy\__init__.py", line 920, in wheel
    wheel = self._wheel_builder.build(self._build_dir)
  File "C:\Users\kieffer\AppData\Local\Temp\build-env-vu8fa4mh\lib\site-packages\mesonpy\__init__.py", line 502, in build
    self._project.build()  # ensure project is built
  File "C:\Users\kieffer\AppData\Local\Temp\build-env-vu8fa4mh\lib\site-packages\mesonpy\__init__.py", line 737, in build
    self._meson('compile', *self._meson_args['compile'],)
  File "C:\Users\kieffer\AppData\Local\Temp\build-env-vu8fa4mh\lib\site-packages\mesonpy\__init__.py", line 657, in _meson
    return self._proc('meson', *args)
  File "C:\Users\kieffer\AppData\Local\Temp\build-env-vu8fa4mh\lib\site-packages\mesonpy\__init__.py", line 652, in _proc
    subprocess.check_call(list(args), env=self._env)
  File "c:\python\3.8\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['meson', 'compile']' returned non-zero exit status 1.

ERROR Backend subprocess exited when trying to invoke build_wheel
```
That said, you mentioned this option can be provided via the `pyproject.toml`: I started my investigation in this way and did not find anything relevant (except redirecting me towards the `--config-setting`which I started with...)

**Comment by dnicolodi** [comment]
This is unexpected. I'm not that familiar with MSVC builds, but in the meson-python test suite and in my projects the default options works just fine. Which compilation environment is this?

**Comment by kif** [comment]
We are building our tools (not only `fabio`, but anything under the silx-kit repos and much more) with a fairly large matrix: Python 3.7, 3.8, 3.9, 3.10 and 3.11 built on Windows x64 with Visual Studio 2019 Developer Command Prompt v16.7.5 / msvc 19.16.27040 "Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27040
It is running in a Gitlab-CI (not public)

**Comment by dnicolodi** [comment]
Do you mean you build your own Python too? I'm curious to understand why you encounter this issue while other projects do not. I build with the default options with the Python provided by the `actions/setup-python` action in the GitHub Actions runners and with `cibuildwheel` also in the GitHub Actions runners (which I believe uses its own Python installations) and the compilation runs fine. Building for Python 3.7 you will likely also bump into https://github.com/mesonbuild/meson/issues/11097

**Comment by dnicolodi** [comment]
Sorry, pressed the wrong button

**Comment by kif** [comment]
Hi Daniele,

Thanks for the documentation. Very useful.

Concerning the build type which was wrong under windows+msvc, no I did
not figure out what was the root of the problem. The fact is, the issue
disappeared with some upgrade.

-- 
Jérôme Kieffer
