### ISSUE TITLE
Add the PyPA discord as an official project communication channel

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson-python#253]
I have created a `meson-python` channel in the "Packaging Related" (meaning it's affiliated with the PyPA) category of the PyPA discord. Is everyone okay in documenting this as one of the official communication channels for the project?

https://discord.gg/pypa

**Comment by rgommers** [comment]
What does "official" mean here? If you want to use it as a venue for answering questions that seems perfectly fine to me, but I don't really want to be on Discord (that'd be a second chat app next to Slack for me, and a much noisier one at that). So it'd be great if the design discussions/decisions stayed on GitHub.

**Comment by FFY00** [comment]
Official just means we recognize it and link it in the documentation.

I wouldn't *expect* any of the maintainers to be there. As long as one is a PyPA discord user and is happy to keep up with the channel, it would make sense to have it listed IMO.

Any decisions related to development should stay here, the Discord channel would only be a venue for users to ask questions, etc.

**Comment by eli-schwartz** [comment]
> Official just means we recognize it and link it in the documentation.

I think that works just as well if you recognize it and link to it in the documentation as an *un*official resource.

Usually when people see "official" communication channels they expect that that can be a place to, well, "officially" communicate with the project developers. There's a definitely non-zero chance that people will go to discord to report bugs *instead* of github. Doing the correct messaging will probably be important.

**Comment by dnicolodi** [comment]
I think that an unmanned communication channel is worst than no communication channel. Unless there are a few meson-python expert users on the PyPA discord, I think pointing to as a place where to look for help is not a very good idea. I don't have the bandwidth to be on Discord. If want to add another venue for user questions beside GitHub, I would much prefer the Python Discourse instance.

**Comment by FFY00** [comment]
The Python discourse instance isn't meant for external projects like this, and it wouldn't be much different from just opening an issue anyway. Discord is good for quick questions, etc., if it's something that should be on the issue tracker I just tell the person to open an issue.

**Comment by rgommers** [comment]
Then I'd phrase it as such in the docs, and not call it "official". Proposed docs text: _If you encounter what you think is a bug in `meson-python`, please open an issue on [the issue tracker](https://github.com/mesonbuild/meson-python/issues). Usage questions and potential doc improvements are also welcome on the issue tracker. In addition, the `meson-python` channel on the [PyPA Discord](https://discord.gg/pypa) may be useful for quick questions - one `meson-python` maintainer is active there._
