### ISSUE TITLE
Editable install easy to trip

### ISSUE THREAD

**Issue by HDembinski** [mesonbuild/meson-python#258]
I tried out the editable install feature in the unreleased trunk. It works, congratulations.

However, it seems still a bit brittle. I only got it to work in a pristine repository. At some point I deleted the folder .mesonpy, not knowing that this is required for the editable build. After that I could not reinstall an editable build. I uninstalled the broken version of my package, and then tried to install again and got this error message

```
Using pip 22.3.1 from /Users/hdembinski/Extern/pyhepmc/venv/lib/python3.10/site-packages/pip (python 3.10)
Obtaining file:///Users/hdembinski/Extern/pyhepmc
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Preparing editable metadata (pyproject.toml)
  Directory does not contain a valid build tree:
  /Users/hdembinski/Extern/pyhepmc/.mesonpy/editable/build
  + meson setup --reconfigure --prefix=/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10 /Users/hdembinski/Extern/pyhepmc /Users/hdembinski/Extern/pyhepmc/.mesonpy/editable/build --native-file=/Users/hdembinski/Extern/pyhepmc/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --python.purelibdir /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages --python.platlibdir /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/hdembinski/Extern/pyhepmc/venv/bin/python3.10 /Users/hdembinski/Extern/pyhepmc/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_editable /var/folders/tl/pv6mt7z17tz0stm1fjfg01cc0000gp/T/tmp68h2b2jf
  cwd: /Users/hdembinski/Extern/pyhepmc
  Preparing editable metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I tried running the command 
```
meson setup --reconfigure --prefix=/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10 /Users/hdembinski/Extern/pyhepmc /Users/hdembinski/Extern/pyhepmc/.mesonpy/editable/build --native-file=/Users/hdembinski/Extern/pyhepmc/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --python.purelibdir /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages --python.platlibdir /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
```
by hand, which provides the same error (that is not illuminating).

I got it working again after a `git clean -fX`.

**Edit**: I use the command `pip install --no-build-isolation -v -e .` to install my package. The `--no-build-isolation` is needed to pick up the trunk version of meson-python.

**Comment by rgommers** [comment]
> However, it seems still a bit brittle. I only got it to work in a pristine repository. At some point I deleted the folder .mesonpy, not knowing that this is required for the editable build. After that I could not reinstall an editable build.

I think that that can be considered a bug, even though manually deleting `.mesonpy/` isn't an obvious user action to take. I can reproduce the problem on SciPy:
```bash
$ pip install --no-build-isolation -v -e .  # works
$ pip install --no-build-isolation -v -e .  # rerunning still works
$ rm -rf .mesonpy/
$ pip install --no-build-isolation -v -e .  # no longer works:
```
If `.mesonpy/` doesn't exist, then treating it like a fresh build and running `meson setup` rather than `meson reconfigure` should avoid this issue I think.

**Comment by lithomas1** [comment]
Looks like #257 will address this.

I will note that I can't always reproduce this, since sometimes it will work even after deleting .mesonpy.

**Comment by dnicolodi** [comment]
This has been fixed and we have tests in  place to make sure it does not regress.
