### ISSUE TITLE
Consider dropping direct references to PEP 517

### ISSUE THREAD

**Issue by pradyunsg** [mesonbuild/meson-python#264]
See https://discuss.python.org/t/name-for-pyproject-toml-builds-and-peps/1659 for the rationale.

Basically, we've been moving to a world where "pyproject.toml-based builds" is a much more consistent and better way to refer to such build-backends. We don't need to point users to dense design documents to understand how stuff works.

**Comment by rgommers** [comment]
+1 we should do that, thanks @pradyunsg
