### ISSUE TITLE
How does `sdist` work ?

### ISSUE THREAD

**Issue by kif** [mesonbuild/meson-python#271]
Hi,
I just realized `python -m build -s` calls `meson dist` which does not take into account the content of `MANIFEST.in`.
Can you confirm that ?
I wish to exclude from the source release (sdist) all code related to continuous integration and I did not find an easy way to do so with meson-python ... 
Cheers,
Jerome

**Comment by rgommers** [comment]
Yes, that is correct. `MANIFEST.in` is `distutils`/`setuptools`-specific.

> I wish to exclude from the source release (sdist) all code related to continuous integration and I did not find an easy way to do so with meson-python ...

You can use `export-ignore` in `.gitattributes`. See, e.g., for SciPy: https://github.com/scipy/scipy/blob/main/.gitattributes

**Comment by rgommers** [comment]
It already has this info in the docs (https://meson-python.readthedocs.io/en/latest/index.html#source-distribution-sdist). So I'll close this issue. If there's more to discuss, please feel free to comment more.
