### ISSUE TITLE
Config setting name suggestion

### ISSUE THREAD

**Issue by henryiii** [mesonbuild/meson-python#275]
Currently, there's a `builddir` option and an `editable-verbose` option for config-settings. I think it would be more internally consistent to rename `builddir` to `build-dir`. I'm adding the equivalent setting to scikit-build-core, and I've always used dashes for multiple names in settings there, and it's got several `-dir` settings, so there I want it to be `build-dir`, and it would be nice if the same setting did the same thing in both packages, IMO. Thoughts?

**Comment by rgommers** [comment]
This sounds like a better name to me. If we do that, we should keep `builddir` as an alias though, because it's already used in the wild.

**Comment by henryiii** [comment]
@dnicolodi Thanks for getting to this!
