### ISSUE TITLE
Warn on unknown config options

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson-python#28]
Just made a type and passed `buildir` insted of `builddir`, causing me to having to rebuild SciPy :upside_down_face: 

We should warn, or even error out, if an unrecognized config option is passed.

**Comment by rgommers** [comment]
Erroring out sounds good to me, if there's an easy way to get meson to do that.

**Comment by dnicolodi** [comment]
meson-python correctly errors out on unrecognized options now. Options passed to meson with the `setup-args=-Dfoo=bar` syntax cause meson to return with an error. I think this is fixed.
