### ISSUE TITLE
The `subdirs` test package most likely does not test what it is intended to test

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson-python#295]
The `subdirs` test package installs some Python code https://github.com/mesonbuild/meson-python/blob/fc7245d66186e244681cb0e10dfcaacd4fbb8d0e/tests/packages/subdirs/meson.build#L13-L18

However, for how `install_sources()` works, all the files are installed by Meson as top level modules and not as nested packages, as the name of the test package would suggest, with later instances of the files names `__init__.py` and `c.py` overwriting earlier instances.

What was this test package supposed to test? The `scipy-like` test package already contains a test for nested packages. I'm tempted to just delete this test package.

**Comment by rgommers** [comment]
That seems like a wrong test indeed. It would do the right thing if it would have the `preserve_path` keyword, added in `0.64.0`: https://mesonbuild.com/Release-notes-for-0-64-0.html#added-preserve_path-arg-to-install_data. So adding that would be the alternative to deleting it.

**Comment by dnicolodi** [comment]
Unless I'm missing something, this test package is used only here https://github.com/mesonbuild/meson-python/blob/fc7245d66186e244681cb0e10dfcaacd4fbb8d0e/tests/test_sdist.py#L32-L44 to test the generation of an sdist, thus the fact that a wheel generated from that package would not make much sense is not really relevant. On the other hand, I don't understand why we need to test that subdirs are included in the sdist. However, I don't see anything in the sdist generation that may trip over the archive containing subdirectories.

We cannot use `preserve_path` unless we bump the minimum required Meson version from 0.63.3 to 0.64. I don't know if it is worth doing only for this.

**Comment by FFY00** [comment]
I think I added this in the beginning to make subdirs would get indeed copied to the sdist. We can bump to 0.64 in tests only and add `preserve_path`, and add a wheel test.

**Comment by dnicolodi** [comment]
I found this yesterday late when I was looking for a test package that actually installs a Python package (it is funny that almost none of the test packages do that) to use in the tests for the editable wheels. I wanted to annotate it somewhere to do not forget in case it was relevant. For how the test package is used, it does not seem to be relevant.

I like the possibility to run the tests without to much trickery with the oldest supported Meson. I'll fix this up later today. Most likely just splitting up the `py.install_sources()` call into multiple calls and leaving a note saying that we could use `preserve_path` in later Meson versions.
