### ISSUE TITLE
Should compilation backends different than `ninja` be supported?

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson-python#324]
meson-python injects a build dependency on `ninja` if it detects that `ninja` is not available. Thus it seems that it implicitly assumes that the meson build backed used is exclusively `ninja`. This is fine. However, the project compilation is initiated with the `meson compile -C $builddir` command, which is the backend-agnostic way offered by Meson to compile a project. Should this command be replaced by `ninja -C $builddir`? There isn't much difference, except that invoking `ninja` directly is potentially much faster. This is relevant for editable wheel installations, where the project rebuild is triggered on import.

**Comment by rgommers** [comment]
The difference on my machine for SciPy is ~200 ms - that's user-noticeable. So this may make sense to do. It's a tradeoff - but I'm inclined to say that we could make this change, and if really needed add a config option to get the best of both worlds.

**Comment by dnicolodi** [comment]
A config option for what exactly?

**Comment by rgommers** [comment]
For users who need the ability back to use `samurai` for example. I'm not sure if we have any of those users, but they could get a config option to either call `samurai` directly or to go back to `meson compile`.

**Comment by rgommers** [comment]
So to clarify, I'm saying: it should be fine to do this now, and don't worry about a config option until anyone complains.

**Comment by dnicolodi** [comment]
meson-python already obeys the `$NINJA` environment variable, I would keep support for that. Note that the environment variable is also the only way AFAIK to have `meson compile` use `samurai` instead of `ninja`. I was thinking more about users wanting to use the Visual Studio or Xcode backends.

**Comment by eli-schwartz** [comment]
> I was thinking more about users wanting to use the Visual Studio or Xcode backends.

Really, the only time you'd ever want to use alternative meson backends is when you're using them for IDE features. This is unlikely to happen from pip install or from pyproject-build, and you'd have to sneak the backend in via `setup-args` which seems janky and also again, why would one even bother.

IMHO it's fine for meson-python to document that one should simply not do that, and then use the direct ninja path.
