### ISSUE TITLE
Default `meson setup` arguments

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson-python#329]
Currently, we default to `-Ddebug=false -Doptimization=2`. When we did this, see #27, we always meant to add a way to disable it and allow customizing the options. In #167, we added a way to pass arguments to Meson, but we didn't revisit this.

https://github.com/mesonbuild/meson-python/blob/f9dc18f85475e80e4cba31105cbe6a4e42660b78/mesonpy/__init__.py#L812-L814

So, we need to figure out how this should be configured, and if we should actually have different behaviors, for editable builds for eg.

My initial proposal would be to add a `tool.meson-python.args.remove-defaults` (alternative name suggestions welcome) setting, which would remove the default arguments. This option would be enabled by default on editable builds, and disabled by default on normal builds.

**Comment by dnicolodi** [comment]
I don't think we need this. Setting aside the minor issue that I think this is an horrible user interface, there is really no need to remove the default settings, the settings can be simply overridden with the user preferred settings: Meson processes the command line arguments in the order they are specified and later options have precedence on earlier ones.

I also think meson-python should not have different default settings for normal and editable wheels. It seems unnecessary and it just going to add confusion. I think meson-python should stay as much as possible out of the way in deciding how things are compiled.

**Comment by rgommers** [comment]
I think I agree with @dnicolodi, we have enough knobs here, and the overrides are even documented now (e.g., https://meson-python.readthedocs.io/en/latest/how-to-guides/meson-args.html#set-the-build-optimization-level-to-3).

Close?

**Comment by FFY00** [comment]
Yes, though we still need to order the Meson arguments correctly, to allow users to just override the ones they're supposed to. I'll open a new issue to track that.
