### ISSUE TITLE
Use an autoformatter

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson-python#347]
I'd swear we had [black](https://github.com/psf/black) setup, but I guess not??

Anyway, having an autoformatter makes sure the codestyle is consistent across the whole codebase. I think [black](https://github.com/psf/black) is the best option.

**Comment by rgommers** [comment]
I've given up having strong opinions about style issues (life's too short:)). I'm happy to go with whatever other folks prefer.

**Comment by rgommers** [comment]
It seems like there isn't consensus that this is a good idea or worth the code churn. We have two closed PRs that tried to deal with code style more, and we've already got some checkers in CI and the code is generally already in quite good shape. So let me close this one as wontfix.
