### ISSUE TITLE
Skip subprojects when building the wheel

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/meson-python#35]
`WARNING File could not be mapped to an equivalent wheel directory: /tmp/mesonpy-udbdqxaw/install/usr/lib64/libxxhash.a ({libdir_static}/libxxhash.a)`

Example project: https://github.com/hse-project/hse-python. Use the `tristan957/mesonpy` branch.

**Comment by dogtopus** [comment]
I also have a upcoming project that can benefit from this. Currently I have pure-static external subprojects which there's currently no way to skip the installation on the meson side other than specifying `--skip-subprojects`. It's fine (although hacky and error prone) when manually invoking meson but with a builder script it becomes a problem.

**Comment by FFY00** [comment]
Hi @tristan957 and @dogtopus, thank you for opening this issue, and sorry for the late reply. There is no location in wheels for static libraries, and they aren't needed at runtime, so we should probably just ignore them. I will try to look into a PR tomorrow.

**Comment by tristan957** [comment]
Very cool. Happy to see some movement on this issue

**Comment by rgommers** [comment]
> There is no location in wheels for static libraries, and they aren't needed at runtime, so we should probably just ignore them. I will try to look into a PR tomorrow.

I should have commented on this earlier, but: this statement is unfortunately not 100% accurate. NumPy ships static libraries (`libnpymath.a` and `libnpyrandom.a`) that live inside `site-packages/numpy/`. Rebuilding those from source for consuming libraries is highly nontrivial, so I don't think that NumPy will be able to get rid of them very easily. 

Shipping static libraries is obviously not the best design, and it makes assumptions about the compiler toolchain that consumers are using (must be MSVC-compatible on Windows, GCC-compatible on Linux and Clang-compatible on macOS).

I suspect that when NumPy moves to Meson, we can probably work around this problem by not using `static_library(..., install: true)` (which I think is what produces `{libdir_static}`) but `custom_target`.
