### ISSUE TITLE
Parallel use of interpreters on editable installs

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson-python#380]
Currently, in editable installs, we just rebuild the project the first time to avoid mismatched versions of modules from bring loaded. No safeties are in place when running multiple at the same time, though, allowing module mismatches to happen if the project is rebuilt by a different interpreter.

My proposal would be for us to not rebuild the project when it is being used by other interpreter, and raise a warning informing the user of this.

**Comment by rgommers** [comment]
Should be addressed well enough by gh-387, which adds the ABI tag to the install path.
