### ISSUE TITLE
Cross-compiling using ARCHFLAGS raises FileNotFoundError

### ISSUE THREAD

**Issue by ianthomas23** [mesonbuild/meson-python#406]
I am trying out cross-compiling on macOS using `ARCHFLAGS` and I receive a `FileNotFoundError` when `meson-python` tries to write the `cross-file` as the build directory hasn't been created yet.

The relevant code in `meson-python/mesonpy/__init__.py` is here
https://github.com/mesonbuild/meson-python/blob/55afbc0ed38a5f403ffb033b6fe8e2451c40ec27/mesonpy/__init__.py#L682
where the cross-file is being written, but it precedes where the build directory is created here
https://github.com/mesonbuild/meson-python/blob/55afbc0ed38a5f403ffb033b6fe8e2451c40ec27/mesonpy/__init__.py#L699-L700

An example of it is in this github action: https://github.com/ianthomas23/contourpy/actions/runs/4768726328/jobs/8478377421. This is using `cibuildwheel` to build an `x86_64` wheel and then an `arm64` one on an `x86_64` runner. The former succeeds and the latter, being cross-compiled, fails.

I can also reproduce this locally using
```
ARCHFLAGS="-arch x86_64" pip install -v .
```
from the `meson` branch of https://github.com/ianthomas23/contourpy

**Comment by dnicolodi** [comment]
Thanks for reporting the issue. It should be fixed by #407. I added a test to make sure this does not regress again, and in doing so I found another bug...

**Comment by ianthomas23** [comment]
Thanks for fixing this so quickly.

**Comment by rgommers** [comment]
+1 thanks from me too. It looks like we should do a 0.13.1 very soon. I can take care of that.

**Comment by dnicolodi** [comment]
I wanted to suggest a 0.13.1 release too. Maybe we can wait a little to see if we want to include a mitigation for #409.

**Comment by rgommers** [comment]
Makes sense. Let's give it a couple of days. Now that I know what the release process is though, it's not much work. As long as `main` is in a releasable state of course.

**Comment by dnicolodi** [comment]
@rgommers I think we can release 0.13.1 from current `main`. I'll see if I can find a few minutes to prepare a PR with the changelog entry and the version bumps.

**Comment by rgommers** [comment]
Sounds good. Thanks for the ping. I'd like to do this today indeed, because I'm traveling for a couple of days from tomorrow.

**Comment by rgommers** [comment]
Release is up now: https://pypi.org/project/meson-python/0.13.1/, https://github.com/mesonbuild/meson-python/releases/tag/0.13.1

**Comment by dnicolodi** [comment]
Thanks @rgommers !
