### ISSUE TITLE
Add option to automatically include all .py files

### ISSUE THREAD

**Issue by dstansby** [mesonbuild/meson-python#411]
As far as I can tell every `.py` file to be included in a build distribution needs to be manually specified in a `meson.build` file, e.g. see this example from scipy:

https://github.com/scipy/scipy/blob/5db471907f7d2e838c5c073c45928885e127ecec/scipy/optimize/meson.build#L260

It would be great to have an option to include all `.py` files without having to manually list them all in the build files.

**Comment by rgommers** [comment]
See https://mesonbuild.com/Reference-manual_functions.html#install_subdir for that functionality. 

This is a trade-off between convenience and robustness/performance. Explicit listing gives more control (e.g., no stray files can be included in an sdist/wheel, unlike a `*`-include).

**Comment by dstansby** [comment]
👍 thanks - would be good to put a quick note in the `meson-python` notes pointing to that function.

**Comment by rgommers** [comment]
Hmm, I'd prefer not to - Meson has a lot of functionality, and has lots of docs - it's hard to figure out what folks might need. I'd rather say "anything in a `meson.build` file is described in the Meson docs.

Also, the pandas Meson setup (`https://github.com/pandas-dev/pandas/pull/49115`) uses `install_subdir`, so we'll point to that as another example soon.

**Comment by dstansby** [comment]
Fab - I think pointing to the pandas example will be good enough here, thanks for the quick replies and I'll close this!

**Comment by rgommers** [comment]
great, thanks!
