### ISSUE TITLE
Building pyodide packages

### ISSUE THREAD

**Issue by stefanv** [mesonbuild/meson-python#418]
This issue is to raise awareness of the fact that pyodide cannot currently build packages with meson.

- [pyodide issue](https://github.com/pyodide/pyodide/issues/2096), no detail
- [scikit-build issue](https://github.com/scikit-build/scikit-build/issues/663), no detail
- [Attempt at building skimage](https://github.com/pyodide/pyodide/pull/3874)

I spoke briefly to @henryiii, and it sounds like a cross build definition file is necessary. I'd like to gather more information on what is needed to support pyodide builds.

**Comment by rgommers** [comment]
Thanks for this issue @stefanv. The scikit-image 0.20.0 build in the PR that is your third link above passes, with one minor patch that may not even be needed. I commented in https://github.com/pyodide/pyodide/pull/3874#issuecomment-1560708984.

Let's see if that patch can indeed be removed. The one other thing we can/should do is document how to use a cross file for Pyodide. There doesn't seem to be anything nonstandard there though, and meson cross file usage has good docs at https://mesonbuild.com/Cross-compilation.html.

**Comment by stefanv** [comment]
This is excellent progress; thanks for your advice on the skimage build.
