### ISSUE TITLE
Error when filtering install tags on install targets with no tag

### ISSUE THREAD

**Issue by bruchar1** [mesonbuild/meson-python#421]
```
mesonpy\__init__.py", line 860, in _install_plan
    if details['tag'].strip() not in install_tags:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'

ERROR Backend subprocess exited when trying to invoke build_wheel
```

It occurs because some targets in intall_plan have `null` tag.

For an example, it occurs when I try to build wheel for https://github.com/bruchar1/pypkgconf

**Comment by dnicolodi** [comment]
I wonder whether the `strip()` call is needed at all. Why would introspection data contain install tags with spurious spaces?

**Comment by bruchar1** [comment]
> I wonder whether the `strip()` call is needed at all. Why would introspection data contain install tags with spurious spaces?

In theory, it is possible to write `install_tag: ' silly '` in the meson.build file, but meson strips values passed to `--tags` argument of `install`. Therefore, it wouldn't work...
