### ISSUE TITLE
meson `--skip-subprojects` option ignored when building wheel

### ISSUE THREAD

**Issue by bruchar1** [mesonbuild/meson-python#423]
My project use a subproject, and the subproject installs a static lib. I don't want to include the static lib, or any file installed by the subproject. Howerver, adding
```
[tool.meson-python.args]
install = ['--skip-subprojects']
```
to pyproject.toml does not prevent meson-python trying to install files from the subproject:

```
+ meson install --quiet --no-rebuild --destdir C:\Users\CHARLE~1.BRU\AppData\Local\Temp\build-via-sdist-03nfoz4f\pypkgconf-0.1.0\.mesonpy-tmvd08tf\install --skip-subprojects

meson-python: error: Could not map installation path to an equivalent wheel directory: '{libdir_static}\\libpkgconf.a'

ERROR Backend subprocess exited when trying to invoke build_wheel
```

For reference, my project is on https://github.com/bruchar1/pypkgconf

**Comment by bruchar1** [comment]
`meson install` seems to be invoked before the files for the wheel are collected. I wonder if, instead of having special treatments for every meson switch, we could simply compare the file list from the install plan with the files copied to the temp install dir? This would allow to remove the special handling for `--tags`, and to support any special install switches meson could support in the future.

Otherwise, this should be documented that `--skip-subprojects` is not supported.

**Comment by dnicolodi** [comment]
This is precisely what I meant with revisting the architecture of this part of meson-python. meson-python currently does not do anything with the results of `meson install`. The build artifacts are collected from the source directory and from the build directory. It is a long standing bug in meson-python that we need to correct. #348 and #364 fix that. The fix for this issue would have to build on top of these patches.

**Comment by dnicolodi** [comment]
Thinking about this a bit more, the solution is not as easy as I though: in several places we need to know which files will be included in the wheel before we run `meson install` and start populating the wheel file. We even need it before running the compilation, for determining if we need to inject a build dependency on `patchelf` on Linux.

Unfortunately, I don't see an easy way to implement the equivalent of `--skip-subprojects` with only the information available in the Meson introspection data. I don't know how to implement this functionality within these constraints.

**Comment by dnicolodi** [comment]
See https://github.com/mesonbuild/meson/pull/11909
