### ISSUE TITLE
Configuration data are not installed for editable builds

### ISSUE THREAD

**Issue by ngoldbaum** [mesonbuild/meson-python#429]
I ran into this in the context of numpy: https://github.com/numpy/numpy/issues/23981#issuecomment-1601127264

Here's a test that you can add to `test_editable.py`:

```
def test_editable_configure_data(venv, editable_configure_data):
    venv.pip("install", os.fspath(editable_configure_data))
    path = (
        pathlib.Path(__file__).parent
        / "packages"
        / "configure_data"
        / "configure_data.py"
    )
    code = path.read_text()
```

It currently fails with the following error:

```
_________________________ test_editable_configure_data __________________________

venv = <tests.conftest.VEnv object at 0x7f5d565bfbb0>
editable_configure_data = PosixPath('/tmp/pytest-of-nathan/pytest-3/test0/mesonpy-test-339vlpxw/configure_data-1.0.0-py3-none-any.whl')

    def test_editable_configure_data(venv, editable_configure_data):
        venv.pip("install", os.fspath(editable_configure_data))
        path = (
            pathlib.Path(__file__).parent
            / "packages"
            / "configure_data"
            / "configure_data.py"
        )
>       code = path.read_text()

tests/test_editable.py:203: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../.pyenv/versions/3.10.9-debug/lib/python3.10/pathlib.py:1134: in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = PosixPath('/home/nathan/Documents/meson-python/tests/packages/configure_data/configure_data.py')
mode = 'r', buffering = -1, encoding = 'locale', errors = None, newline = None

    def open(self, mode='r', buffering=-1, encoding=None,
             errors=None, newline=None):
        """
        Open the file pointed by this path and return a file object, as
        the built-in open() function does.
        """
        if "b" not in mode:
            encoding = io.text_encoding(encoding)
>       return self._accessor.open(self, mode, buffering, encoding, errors,
                                   newline)
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/nathan/Documents/meson-python/tests/packages/configure_data/configure_data.py'
```

**Comment by dnicolodi** [comment]
> I ran into this in the context of numpy: [numpy/numpy#23981 (comment)](https://github.com/numpy/numpy/issues/23981#issuecomment-1601127264)

Editable build do not install build artifacts. Editable builds rely on a Python module loader to fetch code and data files from the build or source directory. This cannot make data files available via paths constructed from the location of python modules, except in some fortunate cases. In particular, the header files installed by Numpy cannot be made available in the expected location. This is a limitation of editable installs as implemented in meson-python. It can be argued that installing header files as part of Python packages is not covered by the Python wheel specification, thus it is undefined behavior. 

> Here's a test that you can add to `test_editable.py`:
> 
> ```
> def test_editable_configure_data(venv, editable_configure_data):
>     venv.pip("install", os.fspath(editable_configure_data))
>     path = (
>         pathlib.Path(__file__).parent
>         / "packages"
>         / "configure_data"
>         / "configure_data.py"
>     )
>     code = path.read_text()
> ```

This is not supposed to be working. In general accessing data files constructing a path via `__file__` is not something to rely on. Doing so outside the boundaries of a package is really asking for trouble.

**Comment by ngoldbaum** [comment]
OK, fair enough. I'll flag it as something that should be mentioned in the numpy docs. I think there are a lot of people relying on editable builds of numpy for development work in other packages, so this will likely impact more people in the future.
