### ISSUE TITLE
Detection of limited API modules does not work on Windows

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson-python#449]
Currently meson-python uses the Python extension module filename suffix to determine if these use the Python limited API. This works on Linux and macOS where the extension contains an explicit `abi3` tag. However, there is not such a thing on Windows, where the filename suffix used for limited API extension modules is just `.pyd`.

We could tweak the heuristic and assume that if the extension module filename suffix does not contain a platform tag it is targeting the limited API. However, IIRC until Python 3.9 there are no platform tags in the extension filenames on Windows. We may need to find an explicit way for the user to signal that a package targets the limited API, or we need a way for Meson to add this information to the metadata.

This is not yet a concrete problem, because Meson does not yet have an easy way to build extension modules targeting the limited API, but a PR implementing it has already been submitted.

**Comment by rgommers** [comment]
Ah yes, xref https://github.com/mesonbuild/meson/pull/11745. I think it's possible for the build to produce a mix of limited API and default C API using extensions. Meson doesn't have the concept of a Python package, so it seems difficult for it to tell us.

Also, I'm not a big fan of heuristics. Probably easy enough for us to add a config setting for this?

**Comment by dnicolodi** [comment]
We can find a way for Meson to add the information in the metadata we already use to build the wheel.
