### ISSUE TITLE
Document environment variables used by Meson

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson-python#460]
See https://github.com/mesonbuild/meson-python/issues/459#issuecomment-1692971600

Add a note about environment variables injected by conda.

**Comment by rgommers** [comment]
- the environment variables used by `meson-python` are documented at https://mesonbuild.com/meson-python/reference/environment-variables.html
-  the environment variables used by `meson` are documented at https://mesonbuild.com/Reference-tables.html#compiler-and-linker-flag-environment-variables
- the note on Conda injecting environment variables is present on https://mesonbuild.com/meson-python/how-to-guides/debug-builds.html

The main thing that can be improved still is to cross-link from our docs to the Meson docs on this topic. I'll have a go at that.
