### ISSUE TITLE
macOS cross file is missing Objective-C compiler

### ISSUE THREAD

**Issue by QuLogic** [mesonbuild/meson-python#468]
I'm porting Matplotlib to Meson/meson-python, and one thing we use on macOS that isn't used elsewhere is the objc compiler. When building arm64 wheels on macOS via GitHub Actions, cibuildwheel uses a cross-compiler.

Meson-python correctly sets up a [cross C compiler](https://github.com/matplotlib/matplotlib/actions/runs/6056922010/job/16437518240?pr=26621#step:4:471) and [cross C++ compiler](https://github.com/matplotlib/matplotlib/actions/runs/6056922010/job/16437518240?pr=26621#step:4:473). However, meson [fails to find the objc compiler](https://github.com/matplotlib/matplotlib/actions/runs/6056922010/job/16437518240?pr=26621#step:4:521).

I believe meson-python is missing an entry for it in its automatically-generated cross file.

**Comment by dnicolodi** [comment]
It is easy to add an entry for the `objc` compiler (and maybe `objcpp` too, while we are at it). However, to what command should we set these? The obvious choice would be `objc -arch $arch`, but an `objc` command does not seem to exist.

**Comment by dnicolodi** [comment]
Never mind, `cc` and `c++` seem to do the trick.

**Comment by dnicolodi** [comment]
Can you please test if #470 works as expected?

**Comment by QuLogic** [comment]
Thanks for the update, it looks like 0.14.0 was successful: https://github.com/matplotlib/matplotlib/actions/runs/6095062066/job/16537929593?pr=26621

**Comment by rgommers** [comment]
Thanks for confirming. And great to see a working Matplotlib build!
