### ISSUE TITLE
Incorrect package name in `METADATA`

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson-python#481]
Looking into more simplifications, on the line of the first commits in #480, I bumped into this issue https://github.com/FFY00/python-pyproject-metadata/issues/60  Some more context is here https://github.com/pdm-project/pdm-backend/issues/185 and here https://discuss.python.org/t/change-in-pypi-upload-behavior-intentional-accidental-pebkac/27707 The latter is a very long thread and I didn't even attempt to read it all.

We can fix this bug on the `meson-python` side, but it would be much easier to do once #480 lands.

**Comment by dnicolodi** [comment]
A related issue is that there is no validation of the package name. The allowed names are defined here https://packaging.python.org/en/latest/specifications/core-metadata/#name

**Comment by rgommers** [comment]
> The latter is a very long thread and I didn't even attempt to read it all.

Ouch. Yes, definitely not reading an 84 message thread on what should be a simple thing one would think. Reviewing your PR now.

**Comment by rgommers** [comment]
Both package name handling and validation are fixed/implemented in gh-483, so closing.
