### ISSUE TITLE
Passing through project-specific config options

### ISSUE THREAD

**Issue by rgommers** [mesonbuild/meson-python#54]
The docs currently mention one option: https://meson-python.readthedocs.io/en/latest/usage/build-options.html. This is a `meson-python` build option. I am trying to figure out if/how it is possible to pass project-specific options through. For example, in SciPy we have a `meson_options.txt` file containing:
```meson
option('blas', type: 'string', value: 'openblas',
        description: 'option for BLAS library switching')
option('lapack', type: 'string', value: 'openblas',
        description: 'option for LAPACK library switching')
```

I don't think it is currently possible to use those with either `build` or `pip`? Something like:
```bash
$ python -m build "-C--Dblas=mkl --Dlapack=lapack"
```
Note that the `build` docs are a bit fuzzy on `-C--` for config settings, or how to pass on multiple settings.

Is this possible at all, or is it planned for the future?

**Comment by FFY00** [comment]
Yes, I am working on it, but that will play with the default Meson options in the config file and I am struggling to decide on the design.

Passing multiple backend config options in pypa/build works just like in Meson with `-D`, it ends up looking a bit weird but there isn´t much we can do about that.

```
$ python -m build -C-Dblas=mkl -C-Dlapack=lapack
```

**Comment by rgommers** [comment]
Cool, good to know. This one is not urgent, it's more a nice-to-have for SciPy 1.9.0 I'd say.

**Comment by andyfaff** [comment]
I'm currently trying to setup [cibuildwheel infrastructure for scipy](https://github.com/andyfaff/scipy/pull/28).
The scipy [pyproject.toml](https://github.com/andyfaff/scipy/blob/cibw2/pyproject.toml) specifies the use of `mesonpy` as the build backend (ultimately using meson/ninja underneath). cibuildwheel just asks `pip` or `build` to make the wheel.

However, in order to target `cp3*-macosx_arm64` cross compilation has to be used, because there is an `arm64` host on an `x86_64` build machine (Github Actions). This requires the use of a [cross-compile file](https://mesonbuild.com/Cross-compilation.html#changing-cross-file-settings). I can find documentation on how to supply this file directly to a meson build (I think it gets placed in the build directory). However, there doesn't seem to be a way of supplying the cross-compile file as options to a `pip/build`.

e.g. I can't do:
```
python -m build . <my_cross_compile_build_flags_to_be_supplied_to_meson>
```

Will this PR enable this?

**Comment by rgommers** [comment]
@andyfaff I believe it should, with `python -m build . -C--cross-file=/absolute/path/to/cross-file.ini`. That should pass it to `meson setup` just fine. There may be one hiccup to work out though (I'm very much not sure without testing): since `meson-python` itself uses a `native-file.ini`, that may conflict. If so, meson-python should probably detect if a cross-file option is present, and leave out its own native-file.

**Comment by eli-schwartz** [comment]
Meson can use both native and cross files at the same time, although it's not especially useful unless the project in question actually has some components tagged as native-only. It's sometimes useful, though, to have e.g. code generator programs that are built for the build machine, not the cross-compile target. Meson therefore allows you to look up native dependencies/programs too, use the native file to configure it, etc.

**Comment by andyfaff** [comment]
One thing I forgot to ask, is it possible to provide flags to the build process via an environment variable? Taking the [above example](https://github.com/FFY00/meson-python/issues/54#issuecomment-1202258344) is it possible to do something along the lines of:

```
export MESON_OPTIONS="--cross-file=/absolute/path/to/cross-file.ini"
python -m build .
```

**Comment by rgommers** [comment]
No, that is not possible, it's a conscious design choice: https://mesonbuild.com/Contributing.html#environment-variables. There are exceptions, like `CC`, `CFLAGS`, `LDFLAGS`, etc. - but not many.

**Comment by eli-schwartz** [comment]
If this PEP 517 backend wanted to, it could read the environment variable and pass it to Meson.

Although that would mean it diverges from Meson's conscious design choice...

**Comment by rgommers** [comment]
I'd much prefer to stay with the Meson philosophy. gh-122 should already solve this problem.

**Comment by doronbehar** [comment]
> @andyfaff I believe it should, with `python -m build . -C--cross-file=/absolute/path/to/cross-file.ini`. That should pass it to `meson setup` just fine.

I too need to add a `--cross-file` flag to meson for cross compiling scipy but there is no `build` module there.. What am I missing? I'm using NixOS and our build scripts use by default:

```
python -m pip wheel --verbose --no-index --no-deps --no-clean --no-build-isolation --wheel-dir dist .
```

Alternatively, how to add `--cross-file` if I want to use `pip build`?

**Comment by andyfaff** [comment]
Try and follow https://github.com/scipy/scipy/blob/acd1a4ad9e8d41d4956baf5fac38a8c779debcda/.github/workflows/wheels.yml#L159, that'll give the clearest example of how to do a cross compilr
