### ISSUE TITLE
Update documentation on readthedocs to redirect to GitHub Pages

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson-python#564]
I don't have permissions to change the URL to the Github Pages hosted documentation.

Also, how hard would it be to redirect from the Read The Docs URL to the Github Pages one? AFAIK, the documentation on Read The Docs is not being updated anymore and it may be confusing for the users.

**Comment by rgommers** [comment]
> I don't have permissions to change the URL to the Github Pages hosted documentation.

I fixed the link, and upgraded your permissions so you should now have access. Also, can I add you on PyPI (and if so, to make sure: this is you right: https://pypi.org/user/dnn/)?

> Also, how hard would it be to redirect from the Read The Docs URL to the Github Pages one? AFAIK, the documentation on Read The Docs is not being updated anymore and it may be confusing for the users.

Last time I looked at this it wasn't possible to add a straight redirect, but for `numpy` we replaced the docs with a manual notice that the docs had moved: https://numpy.readthedocs.io/en/latest/. We could do that?

**Comment by dnicolodi** [comment]
> I fixed the link, and upgraded your permissions so you should now have access. 

Thanks @rgommers for the trust.

> Also, can I add you on PyPI (and if so, to make sure: this is you right: https://pypi.org/user/dnn/)?

Yes, that's me.

**Comment by lazka** [comment]
I did something similar for another project recently, this worked for me:

![image](https://github.com/mesonbuild/meson-python/assets/991986/c90e8767-badc-4f8a-a1ef-1bef7495657b)

**Comment by dnicolodi** [comment]
@rgommers Have you had a chance to look at the solution proposed by @lazka ?

**Comment by rgommers** [comment]
This is fixed now. Sorry it took so long. Thanks for the example @lazka, that worked like a charm.

**Comment by dnicolodi** [comment]
Thanks @rgommers !
