### ISSUE TITLE
Release 0.16.0?

### ISSUE THREAD

**Issue by QuLogic** [mesonbuild/meson-python#603]
I wonder if it would be possible to make a 0.16.0 release; there appears to be nothing open on the milestone (other than issue once I open it).

I'm mostly interested in #527, but there are a few other bug fixes from a while ago that would be good to get out there.

**Comment by rgommers** [comment]
Thanks for the pings @QuLogic. Yes we should - I'm horribly behind on PR reviews (the "last mile effect" from numpy 2.0 is taking its toll), and I think we'd like to get some of those in - gh-594 in particular.

Let me try and get that done over the next few days. It'd be good to set a goal of getting a release out this week. WDYT @dnicolodi?

**Comment by dnicolodi** [comment]
It would be nice to get a release out. There are a few PR pending. It would be nice to get these in, but I don't see any reason why we cannot have a release without those. The release process is relatively lightweight, thus we can follow up with another release soon after.

**Comment by rgommers** [comment]
Release is up on PyPI now: https://pypi.org/project/meson-python/0.16.0/ - thanks for the help & patience!

**Comment by dnicolodi** [comment]
Thanks for taking care of the release!

**Comment by dnicolodi** [comment]
Something went wrong with publishing the documentation. I'm having a look
