### ISSUE TITLE
`tool.meson-python.limited-api` does not produce ABI3 names

### ISSUE THREAD

**Issue by sdimovv** [mesonbuild/meson-python#643]
`meson-python` version: 0.16.0

I enabled the [limited-api](https://mesonbuild.com/meson-python/reference/pyproject-settings.html#cmdoption-arg-tool.meson-python.limited-api) option in my `pyproject.toml` like so:

```toml
[tool.meson-python]
limited-api = true
```

I am also building my extension modules with limited API enabled:
```meson
python.extension_module(
   ...
    limited_api: '3.7',
)
```

Then, I build with:

```
python -m build
```

But the produced wheels do not contain the `abi3` in the name. Nor do the `.so` libs inside.

However, if I instead build like so:

```
python -m build -C=setup-args="-Dpython.allow_limited_api=true"
``` 

Both the wheel and the `.so` libs inside are named correctly (contain `abi3` in the name).

**Comment by rgommers** [comment]
Are you using Meson >=1.3.0? Older versions don't support the limited API. If so, can you either share your project or a simplified reproducible example?

You can also look at our test package for limited API support and see what is different from yours:
https://github.com/mesonbuild/meson-python/tree/main/tests/packages/limited-api

**Comment by sdimovv** [comment]
Apologies, this was a misconfiguration on my part.

I had set `'python.allow_limited_api=false'` in the project default options and forgot about it.

**Comment by rgommers** [comment]
Thanks for figuring it out and updating us @sdimovv.
