### ISSUE TITLE
Runtime Import Error on Windows when using static library from subproject with --skip-subprojects

### ISSUE THREAD

**Issue by WillAyd** [mesonbuild/meson-python#666]
An MRE for this issue is https://github.com/WillAyd/capsule_testing/commit/4ff088effc784bfed2229801e8f4ecc989e363af

I am trying to build a python package that uses nanoarrow from the WrapDB, using a static lib. By default, meson-python would throw the error described in https://github.com/mesonbuild/meson-python/issues/423, so I followed the same guidance there and added:

```toml
[tool.meson-python.args]
install = ['--skip-subprojects']
```

To pyproject.toml. While that works for Unix systems, on Windows I now get an [import error](https://github.com/WillAyd/capsule_testing/actions/runs/10490165852/job/29056305926?pr=1#step:4:277) at runtime when trying to load the package.

I'm not sure generally if this is the right approach. Is it a problem that nanoarrow installs by default as a subproject? If not, is there a better way that I should be handling the static library when creating my Python package?

**Comment by dnicolodi** [comment]
To link statically to nanoarrow, you need 
```
nanoarrow_dep = dependency('nanoarrow', static: true)
```

**Comment by WillAyd** [comment]
Ah nice - that's a better way of expressing things. Unfortunately it doesn't have any net impact

**Comment by eli-schwartz** [comment]
I don't really think --skip-subprojects is the correct line of investigation here. The question to ask is what a DLL inspector says about `import capsule_bug`, specifically w.r.t. why it has a DLL load failure.

Is it failing because the cpython import system cannot find the right C-API interface? Is it failing because the DLL is missing DLL dependencies? Is the file malformed?

**Comment by WillAyd** [comment]
Ah ha...that's right @eli-schwartz this is a red herring. The root cause of that issue then goes back to something delvewheel discovered with `msvcp140.dll` on GHA:

https://github.com/adang1345/delvewheel/issues/54

**Comment by dnicolodi** [comment]
AFAIU loading the Python module files on the exact same system where it has been compiled. I know that the GitHub CI images are a mess, but how is it possible that there are two different version of `msvcp140.dll` on the same system and one is found during compilation and the other during execution?

**Comment by WillAyd** [comment]
I don't know a ton about Windows, but from the info in the link I gather that the sequence with which the PATH is searched does not stay consistent...

As far as this issue is concerned, I am happy to close it out. I take it that the approach of using static linkage with `--skip-subprojects` is viable for packaging

**Comment by eli-schwartz** [comment]
> I know that the GitHub CI images are a mess, but how is it possible that there are two different version of `msvcp140.dll` on the same system and one is found during compilation and the other during execution?

Do you REALLY have to ask how it is possible for the microsoft toolchain to be doing something incredibly unhelpful and counterintuitive?

**Comment by WillAyd** [comment]
No comment...thanks @dnicolodi and @eli-schwartz !

**Comment by ianthomas23** [comment]
> Ah ha...that's right @eli-schwartz this is a red herring. The root cause of that issue then goes back to something delvewheel discovered with `msvcp140.dll` on GHA:
> 
> [adang1345/delvewheel#54](https://github.com/adang1345/delvewheel/issues/54)

Rather than use the delvewheel workaround, you should probably use matplotlib/matplotlib#28687 instead which is the recommendation from a colleague at Microsoft. Original issue was matplotlib/matplotlib#28551. This is going to affect a lot of compiled packages on Windows, giving hard to diagnose crashes, and is going to rumble on for a long time.
