### ISSUE TITLE
intersphinx object.inv missing

### ISSUE THREAD

**Issue by timhoffm** [mesonbuild/meson-python#693]
We've been using intersphinx to link tp meson-python

```
intersphinx_mapping = {
    'meson-python': ('https://meson-python.readthedocs.io/en/stable/', None),
}
```

Since recently, this results in a sphinx-build error ( e.g. https://app.circleci.com/pipelines/github/matplotlib/matplotlib/33363/workflows/c7423837-956c-4d75-85de-93e55fbdb8a5/jobs/85311):

> intersphinx inventory 'https://meson-python.readthedocs.io/en/stable/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: <!doctype html>')

Actually, https://meson-python.readthedocs.io/en/stable/objects.inv does not exist and is redirected to https://mesonbuild.com/meson-python/

**Comment by timhoffm** [comment]
Thanks.

**Comment by rgommers** [comment]
I just added the redirect that broke this (xref gh-564). I tweaked the redirect now, and it resolves again to the right file. Sorry about that.

Still best to update the link, but things should work now either way.

**Comment by dnicolodi** [comment]
@timhoffm I'm curious and a bit too lazy to grep the matplotlib source code: how do you use interphinx to refer to the meson-python documentation? I only used it to refer to API documentation, and meson-python does not document any API

**Comment by timhoffm** [comment]
Only ``:envvar:`MESONPY_EDITABLE_VERBOSE` `` at https://matplotlib.org/devdocs/devel/development_setup.html#build-options
