### ISSUE TITLE
`test_reproducible` fails

### ISSUE THREAD

**Issue by mtelka** [mesonbuild/meson-python#695]
I'm running tests from `meson-python 0.17.0` sdist and I found that the `test_reproducible` test fails with this message:
```
+ meson dist --allow-dirty --no-tests --formats gztar
Dist currently only works with Git or Mercurial repos
```
It looks like the test expects it is run from the git repo and not from sdist.

**Comment by dnicolodi** [comment]
The test does not try to create an sdist for the meson-python package itself. It uses a temporary git reposiotry that is created on demand for executing the test. Therefore, it does not matter whether the test is executed from a git checkout or from the uncompressed sdist. There are other tests that have similar requirements, thus if only this test is failing something else is likely wrong. Can you please report the complete test log?

**Comment by dnicolodi** [comment]
Oh. I just checked, and indeed the test setup for that particular test is wrong. Sorry for the noise. I'm preparing a fix

**Comment by mtelka** [comment]
I'm glad to see that you are faster with the root causing a fixing than me with providing the log :-).

**Comment by dnicolodi** [comment]
Thank you for the report!

**Comment by dnicolodi** [comment]
I merged the fix. I verified locally that is solves the issue you reported. Unless the failing test causes major downstream issues, I don't think that we will be doing a bugfix release to fix just this. Please let me know if this is a problem.

**Comment by mtelka** [comment]
Thank you for the fix.  It is not a problem at all.  I just deselected [this single test](https://github.com/OpenIndiana/oi-userland/pull/19302/files#diff-ffdd135df98b4490fee2d2c1a4ddd16f75d9c8cc4242ad7601bbabe5d522d80fR39) and so I do not need new release.

**Comment by rgommers** [comment]
Thanks for the quick fix @dnicolodi!

It failed in conda-forge as well, so it's probably going to be annoying for distro maintainers. Easier to do an 0.17.1 than having them all carry a patch with the fix I suspect, so I'm inclined to do an 0.17.1 release.

**Comment by dnicolodi** [comment]
Tests will also start failing as soon as distributors pick up pyproject-metadata 0.9.0 as a dependency: the adaptation of our test to this pyproject-metadata release was merged after we releases 0.17.0. However, that path landed after we bumped the minimum pyproject-metadata version to 0.8.0. I assume that a 0.17.1 release will include only fixes. Thus applying these fixes on a 0.17.1 branch will require some work.

**Comment by dnicolodi** [comment]
By the way, how do you create a branch departing from a specific commit (in the specific case from the 0.17.0 tag) in GitHub?

**Comment by dnicolodi** [comment]
Never mind, it is possible to do it the old fashion way

**Comment by mtelka** [comment]
> @mtelka We just releases version 0.17.1 that fixes this issue and test compatibility with the latest release of pyproject-metadata. If you update to this version you can drop the test exclusion and I would be happy to hear if anything else breaks.

I'm happy to report that all tests for `0.17.1` pass.  Tested with `pyproject-metadata==0.9.0`.  Thank you.

Reference: https://github.com/OpenIndiana/oi-userland/pull/19318
